ALTER TABLE stocks ALTER COLUMN price SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN price DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN min_price SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN min_price DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN max_price SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN max_price DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN daily_change SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN daily_change DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN daily_change_percentage SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN daily_change_percentage DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN year_change SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN year_change DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN year_change_percentage SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN year_change_percentage DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN div_yield SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN div_yield DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN div_share SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN div_share DROP DEFAULT;

ALTER TABLE stocks ALTER COLUMN eps SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN eps DROP DEFAULT;

ALTER TABLE stocks DROP updated_at;
