ALTER TABLE stocks ALTER COLUMN price DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN price SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN min_price DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN min_price SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN max_price DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN max_price SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN daily_change DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN daily_change SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN daily_change_percentage DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN daily_change_percentage SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN year_change DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN year_change SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN year_change_percentage DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN year_change_percentage SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN div_yield DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN div_yield SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN div_share DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN div_share SET DEFAULT 0;

ALTER TABLE stocks ALTER COLUMN eps DROP NOT NULL;
ALTER TABLE stocks ALTER COLUMN eps SET DEFAULT 0;

ALTER TABLE stocks ADD updated_at TIMESTAMP;
