openapi: 3.0.1
servers:
  - url: '{scheme}://api.xxx.com'
    variables:
      scheme:
        description: 'The Investment-API is accessible via https and http'
        enum:
          - 'https'
          - 'http'
        default: 'https'
info:
  description: >-
    This API is to serve the investments platform. An REST API built to be fast, flexible and simple.
  version: 1.0.0
  title: Investment-API
  contact:
    name: WeNeedThePoh
    url: 'https://github.com/WeNeedThePoh'
paths:
  /users:
    get:
      summary: Fetch all users
      tags:
        - users
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                $ref: 'schemas/user.yaml'
              example:
                $ref: 'examples/users.json'
    post:
      summary: Add a new user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/user.yaml'
            example:
              $ref: 'examples/user_post.json'
      responses:
        '200':
          description: The new user data
          content:
            application/json:
              schema:
                $ref: 'schemas/user.yaml'
              example:
                $ref: 'examples/users.json'
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
    get:
      summary: Fetch a specific user
      tags:
        - users
      responses:
        '200':
          description: User data
          content:
            application/json:
              schema:
                $ref: 'schemas/user.yaml'
              example:
                $ref: 'examples/user.json'
    put:
      summary: Update a specific user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/user.yaml'
            example:
              $ref: 'examples/user_put.json'
      responses:
        '204':
          description: The user was updated successfully.
    delete:
      summary: Delete a specific user
      tags:
        - users
      responses:
        '204':
          description: The user was deleted successfully.
  /users/{id}/portfolios:
    parameters:
      - name: id
        in: path
        required: true
    get:
      summary: Get all user's portfolios
      tags:
        - portfolios
      responses:
        200:
          description: User's portfolios
          content:
            application/json:
              schema:
                $ref: 'schemas/portfolio.yaml'
              example:
                $ref: 'examples/portfolios.json'
    post:
      summary: Add a new portfolio
      tags:
        - portfolios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/portfolio.yaml'
            example:
              $ref: 'examples/portfolio_post.json'
      responses:
        200:
          description: The portfolio was added successfully.
          content:
            application/json:
              schema:
                $ref: 'schemas/portfolio.yaml'
              example:
                $ref: 'examples/portfolios.json'
  /users/{id}/portfolios/{id}:
    parameters:
      - name: id
        in: path
        required: true
    get:
      summary: Get user's specific portfolio
      tags:
        - portfolios
      responses:
        200:
          description: User's specific portfolio
          content:
            application/json:
              schema:
                $ref: 'schemas/portfolio.yaml'
              example:
                $ref: 'examples/portfolio.json'
    put:
      summary: Update a specific portfolio
      tags:
        - portfolios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/portfolio.yaml'
            example:
              $ref: 'examples/portfolio_put.json'
      responses:
        '204':
          description: The portfolio was updated successfully.
    delete:
      summary: Delete a specific portfolio
      tags:
        - portfolios
      responses:
        '204':
          description: The portfolio was deleted successfully.
